# Generated by Django 5.2.8 on 2025-11-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0002_blogdetail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='image',
        ),
    ]
