# Generated by Django 5.2.8 on 2025-11-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0004_blogpagetags_blogdetail_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='body',
        ),
    ]
