# Generated by Django 5.2.8 on 2025-12-06 08:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0007_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('image', 0), ('text', 1), ('carousel', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('text', 1), ('author', 1)]], {}), 3: ('wagtail.blocks.StreamBlock', [[('image', 0), ('quotation', 2)]], {})}, null=True),
        ),
    ]
