# Generated by Django 5.2.8 on 2025-12-15 06:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0011_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('info', 0), ('faq', 4), ('text', 5), ('carousel', 8), ('image', 6), ('doc', 9), ('page', 10), ('author', 11), ('call_to_action_1', 15)], blank=True, block_lookup={0: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'This is acontent divider with extra information.'}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic']}), 3: ('wagtail.blocks.StructBlock', [[('question', 1), ('answer', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Frequently Asked Questions', 'max_num': 5, 'min_num': 1}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('text', 5), ('author', 5)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('image', 6), ('quotation', 7)]], {}), 9: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 10: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.HomePage'], 'required': False}), 11: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blogpages.author',), {}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 13: ('wagtail.blocks.PageChooserBlock', (), {}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('text', 12), ('page', 13), ('button_text', 14)]], {'label': 'CTA #1'})}, null=True),
        ),
    ]
