# Generated by Django 5.2.9 on 2025-12-21 18:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0013_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('info', 0), ('faq', 1), ('text', 2), ('carousel', 5), ('image', 3), ('doc', 6), ('page', 7), ('author', 8), ('call_to_action_1', 12)], blank=True, block_lookup={0: ('blocks.blocks.InfoBlock', (), {}), 1: ('blocks.blocks.FAQListBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('text', 2), ('author', 2)]], {}), 5: ('wagtail.blocks.StreamBlock', [[('image', 3), ('quotation', 4)]], {}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 7: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.HomePage'], 'required': False}), 8: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blogpages.author',), {}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 10: ('wagtail.blocks.PageChooserBlock', (), {}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 9), ('page', 10), ('button_text', 11)]], {'label': 'CTA #1'})}, null=True),
        ),
    ]
