# Generated by Django 5.2.8 on 2025-12-22 09:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0014_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('info', 0), ('faq', 1), ('text', 2), ('carousel', 6), ('image', 3), ('doc', 7), ('page', 8), ('author', 9), ('call_to_action_1', 13)], blank=True, block_lookup={0: ('blocks.blocks.InfoBlock', (), {}), 1: ('blocks.blocks.FAQListBlock', (), {}), 2: ('blocks.blocks.TextBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.TextBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('text', 4), ('author', 4)]], {}), 6: ('wagtail.blocks.StreamBlock', [[('image', 3), ('quotation', 5)]], {}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 8: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.HomePage'], 'required': False}), 9: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blogpages.author',), {}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 11: ('wagtail.blocks.PageChooserBlock', (), {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('text', 10), ('page', 11), ('button_text', 12)]], {'label': 'CTA #1'})}, null=True),
        ),
    ]
