# Generated by Django 5.2.9 on 2026-01-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0018_author_locked_author_locked_at_author_locked_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('can_edit_author_name', 'Can edit author name')]},
        ),
    ]
